name: Compile and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: linux

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Publish package
    - name: Compile
      run: dotnet pack -o packaged

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Nuget package
        path: packaged/Complex.ConsoleApp.0.0.1.nupkg
