name: Compile and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Publish package with dynamic version
    - name: Set version
      id: vars
      run: echo "VERSION=0.1.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Compile
      run: dotnet pack -o packaged /p:Version=$VERSION

    # Upload the NuGet package as an artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Nuget package
        path: packaged/Complex.ConsoleApp.$VERSION.nupkg
      env:
        VERSION: ${{ env.VERSION }}

    # # Publish to NuGet.org
    # - name: Publish to NuGet.org
    #   run: dotnet nuget push packaged/Complex.ConsoleApp.$VERSION.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    #   env:
    #     NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
