//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Complex.ConsoleApp {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Complex.ConsoleApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FileInputMissingOrInvalid {
            get {
                return ResourceManager.GetString("FileInputMissingOrInvalid", resourceCulture);
            }
        }
        
        internal static string ComplexityByNamespace {
            get {
                return ResourceManager.GetString("ComplexityByNamespace", resourceCulture);
            }
        }
        
        internal static string ComplexityByAssembly {
            get {
                return ResourceManager.GetString("ComplexityByAssembly", resourceCulture);
            }
        }
        
        internal static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        internal static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        internal static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        internal static string FileComplexity {
            get {
                return ResourceManager.GetString("FileComplexity", resourceCulture);
            }
        }
        
        internal static string TotalComplexity {
            get {
                return ResourceManager.GetString("TotalComplexity", resourceCulture);
            }
        }
        
        internal static string AverageComplexity {
            get {
                return ResourceManager.GetString("AverageComplexity", resourceCulture);
            }
        }
    }
}
